name: Go
on: 
  push:
  release:
    types:
      - published
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        username: '${{ secrets.DOCKER_USER }}'
        password: '${{ secrets.DOCKER_PASS }}'

    - id: tag
      name: Get the tag
      run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

    - name: "Build"
      run: docker build --build-arg COMMIT_SHA=${{ github.sha }} docker push okteto/remote:${{ steps.tag.outputs.TAG }} .

    - name: "Push"
      run: |
        docker push okteto/remote:${{ steps.tag.outputs.TAG }}
      if: ${{ github.event_name == 'release' }}
